[package]
name = "egui_system_theme"
version = "0.1.0"
edition = "2021"

[dependencies]
dark-light = "1.1.1"
egui = "^0.27"
once_cell = "1.19.0"

[target.'cfg(target_os = "linux")'.dependencies]
configparser = "3.0.4"
lightningcss = "1.0.0-alpha.57"
palette = "0.7.6"

[target.'cfg(target_os = "windows")'.dependencies]
windows = "0.56.0"


[dev-dependencies]
egui_demo_app = { git = "https://github.com/emilk/egui.git", tag = "0.27.2", package = "egui_demo_app" }
eframe = { git = "https://github.com/emilk/egui.git", tag = "0.27.2", package = "eframe" }
